services:
  neo4j:
    image: neo4j:4.4
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/${NEO4J_PASSWORD}
  app:
    build: .
    ports:
      - "4000:4000"
    env_file: .env
    depends_on:
      - neo4j
